//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Matzip.rc에서 사용되고 있습니다.
//
#define IDD_MATZIP_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN_DLG                   130
#define IDD_CUSTOM_DLG                  132
#define IDD_SCHEMA_CHECK_DLG            134
#define IDD_SELECT_DLG                  136
#define IDD_DELETE_DLG                  140
#define IDD_SELECT_TAB1                 141
#define IDD_SELECT_TAB2                 142
#define IDD_SELECT_TAB3                 143
#define IDD_INSERT_TAB1                 144
#define IDD_UPDATE_DLG                  146
#define IDD_INSERT_DLG                  147
#define IDD_INSERT_TAB2                 148
#define IDD_DELETE_TAB1                 149
#define IDD_DELETE_TAB2                 150
#define IDD_UPDATE_TAB1                 151
#define IDD_UPDATE_TAB2                 152
#define IDD_SELECT_TAB5                 153
#define IDD_SELECT_TAB4                 154
#define IDD_SELECT_TAB6                 155
#define IDD_UPDATE_TAB3                 156
#define IDD_UPDATE_TAB4                 157
#define IDD_INSERT_TAB3                 158
#define IDD_DELETE_TAB3                 159
#define IDD_INSERT_TAB4                 160
#define IDD_DELETE_TAB4                 161
#define IDC_REGISTER_BUTTON             1002
#define IDC_ID_EDIT                     1003
#define IDC_PW_EDIT                     1004
#define IDC_DATA_LIST                   1005
#define IDC_READ_BTN                    1006
#define IDC_CUSTOM_EDIT                 1008
#define IDC_Query_BTN                   1009
#define IDC_RESULT_LIST                 1010
#define IDC_CUSTOM_BTN                  1012
#define IDC_SCHEMA_CHECK_BTN            1014
#define IDC_Schema_LIST                 1017
#define IDC_Table_COMBO                 1018
#define IDC_SELECT_BTN                  1020
#define IDC_SELECT_MAIN_TAB             1022
#define IDC_LIST1                       1023
#define IDC_RESTNAME_EDIT               1024
#define IDC_FAV_LIST                    1024
#define IDC_password_EDIT               1025
#define IDC_REVIEWID_EDIT               1025
#define IDC_SELECT1_LIST                1026
#define IDC_SELECT1_QUERY_BTN           1027
#define IDC_SELECT2_QUERY_BTN           1028
#define IDC_SELECT3_QUERY_BTN           1029
#define IDC_INSERT_BTN                  1030
#define IDC_PW2_EDIT                    1033
#define IDC_BIRTH_DATE                  1034
#define IDC_NAME_EDIT                   1035
#define IDC_MALE_RADIO                  1036
#define IDC_FEMALE_RADIO                1037
#define IDC_REGISTER_BTN                1038
#define IDC_STAR_SPIN                   1041
#define IDC_STAR_EDIT                   1042
#define IDC_INSERT_MAIN_TAB             1043
#define IDC_INSERT2_QUERY_BTN           1044
#define IDC_CONTENT_EDIT                1045
#define IDC_INSERT2_LIST                1046
#define IDC_REVIEW_ENTER_BTN            1047
#define IDC_DELETE_BTN                  1048
#define IDC_DELETE_MAIN_TABS            1049
#define IDC_DELETE_USER_BTN             1050
#define IDC_DELETE_RESTID_EDIT          1051
#define IDC_DELETE_REVIEWID_EDIT        1052
#define IDC_BUTTON1                     1053
#define IDC_DELETE2_LIST                1054
#define IDC_UPDATE_BTN                  1055
#define IDC_UPDATE_MAIN_TAB             1056
#define IDC_UPDATE_ID_EDIT              1057
#define IDC_UPDATE_PW_EDIT              1058
#define IDC_UPDATE_BIRTH_PICKER         1059
#define IDC_UPDATE_NAME_EDIT            1060
#define IDC_UPDATE_MALE_RADIO           1061
#define IDC_UPDATE_FEMALE_RADIO         1062
#define IDC_STAR_EDIT2                  1067
#define IDC_UPDATE2_QUERY_BTN           1068
#define IDC_RESTID_EDIT                 1069
#define IDC_LOGIN_BTN                   1070
#define IDC_ADMIN_BTN                   1071
#define IDC_SELECT5_QUERY_BTN           1072
#define IDC_RETURN_BTN                  1073
#define IDC_SELECT6_LIST                1073
#define IDC_STATIC_TEXT                 1074
#define IDC_UPDATE4_QUERY_BTN           1075
#define IDC_UPDATE4_LIST                1076
#define IDC_NOT_AGREE_BTN               1078
#define IDC_GOOD_BTN                    1079
#define IDC_AGREE_BTN                   1080
#define IDC_INSERT4_LIST                1081
#define IDC_DELETE4_LIST                1082
#define IDC_INSERT4_QUERY_BTN           1083
#define IDC_DELETE4_QUERY_BTN           1084
#define IDC_REST_LIST                   1085
#define IDC_PHONE_EDIT                  1088
#define IDC_LOC_EDIT                    1090
#define IDC_PRICE_EDIT                  1091
#define IDC_START_EDIT                  1092
#define IDC_END_EDIT                    1093
#define SELECT6_TEXT                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
